### ISSUE TITLE
bug in "analyze" method of sweep_pulsed.py ?

### ISSUE THREAD

**Issue by sandromiano** [intermod-pro/presto-measure#3]
Hi, I was having issues analyzing data acquired with SweepPulsed class in sweep_pulsed.py, in particular was having "division by zero" error and plots were returning all zeros. 

I noticed line 204 being:
`nr_samples = IDX_HIGH - IDX_LOW`

which was causing "t" defined at line 228 to be an empty array (as `IDX_HIGH = -1` by default).

I changed line 204 to:
`nr_samples = len(self.t_arr)`

as well as eliminated lines 223 and 224. Now the analysis method seem to run correctly.
I understand this is now forcing to analyze the whole stored data, including portions with no useful signal, but having to change IDX_LOW and IDX_HIGH in sweep_pulsed.py can get clunky. 

I guess one option would be to pass `IDX_LOW` and `IDX_HIGH` as parameters to the "analyze" method, and have a line of code doing something like:

`if IDX_HIGH < 0: IDX_HIGH += len(self.t_arr) + 1`

to support numpy indexing notation.

**Comment by rikyborg** [comment]
Thanks, working on it.

**Comment by rikyborg** [comment]
Should be fixed. See PR #4 for details.
